### ISSUE TITLE
meaning of hcp200.mat

### ISSUE THREAD

**Issue by giub0** [brain-networks/edge-ts#1]
Hi!
 I wonder the meaning of the variables in hcp200.mat, there's a publication where you explain this?

**Comment by rbetzel** [comment]
hcp200.mat are system labels from https://pubmed.ncbi.nlm.nih.gov/28981612/

Each region/node is assigned to one group label.

**Comment by giub0** [comment]
thank you!
so this labels are not referring to the extensively processed HCP data, right?
